### ISSUE TITLE
hey bro

### ISSUE THREAD

**Issue by Domenick027** [snallapa/personal-website-gatsby#19]
Hey brother, your project looks great. I saw in your code that you designed an app to log in, specifically in snallabot.js. I am curious about how you wrote this code, including some key API interfaces and how you obtained them. If you could share with me, I would greatly appreciate it.

By the way, should I communicate with you via email? Would it be more convenient?

**Comment by snallapa** [comment]
@Domenick027 heyy you have twitter or discord? you can hit me @flurgar on twitter, or @snallapa on discord

**Comment by snallapa** [comment]
otherwise email is fine sahith [.] reddy @gmail.com
